title: Hopa course 2016 tribolium transcriptomics
description: This repository holds the projects page for the Tribolium Transcriptomics group in the Host-Parasite Coevolution module  2016.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
